-- 코드를 입력하세요
SELECT GB.TITLE, GB.BOARD_ID, GR.REPLY_ID, GR.WRITER_ID, GR.CONTENTS, TO_CHAR(GR.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
  FROM USED_GOODS_REPLY GR
    JOIN USED_GOODS_BOARD GB ON GB.BOARD_ID = GR.BOARD_ID
 WHERE GB.CREATED_DATE BETWEEN TO_DATE('20221001', 'YYYY-MM-DD') AND TO_DATE('20221031', 'YYYY-MM-DD')
   --AND GB.CREATED_DATE BETWEEN TO_DATE('20221001', 'YYYY-MM-DD') AND TO_DATE('20221031', 'YYYY-MM-DD')
 ORDER BY GR.CREATED_DATE, GB.TITLE;